num1 = eval(input("the first number"))
num2 = eval(input("the second number"))
num3 = eval(input("the third number"))
print("sum : " + str((num1 + num2 + num3) / 3))
print("sum : " + str(num1 + num2 + num3 ))